import java.util.Random;

public abstract class BankAcc {
    private int accNum;
    private double balance;
    BankAcc ISAAccount;
    private double numberDeposits;
    private double numberWithdrawals;
    private double transactionHistory;

    public BankAcc(double balance, int accNum){

        this.balance = balance;
        Random rand= new Random();
        int nextNum = this.accNum;
        this.accNum= rand.nextInt(99999999);
        if (this.accNum == nextNum)
        {
            this.accNum = rand.nextInt(99999999);
        }
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public double getAccNum() {
        return accNum;
    }
    public double getTransactionHistory() {
        return transactionHistory;
    }

    public void setTransactionHistory(double transactionHistory) {
        this.transactionHistory = transactionHistory;
    }


    public double getNumberDeposits() {
        return numberDeposits;
    }

    public void setNumberDeposits(double numberDeposits) {
        this.numberDeposits = numberDeposits;
    }

    public double getNumberWithdrawals() {
        return numberWithdrawals;
    }

    public void setNumberWithdrawals(double numberWithdrawals) {
        this.numberWithdrawals = numberWithdrawals;
    }



    public void depositMoney(double depositAmount) {
        System.out.println("Please enter the amount you want to deposit: ");
        this.balance += depositAmount;
        this.numberDeposits++; // increment number of deposits each time one is made

    }

    public void withdrawMoney(double withdrawAmount) {

        if(balance < withdrawAmount) {
            System.out.println("Insufficient Funds. \n Please Deposit an Amount.");
        }
        else {
            balance -= withdrawAmount;
            numberWithdrawals++; // increment number of withdrawals made each time money is withdrawn

        }

        //NB ISA accounts can't go below 100, so some logic above to check for an ISA account is needed
    }
//display all bank accounts
    //ask user to input two numbers from account
    //ask user two numbers to account
    //ask user to input amount of money
    public void moneyTransfer(BankAcc fromAccount, BankAcc toAccount, double amountToTransfer){
        if (fromAccount == ISAAccount) {
           //not sure how to validate withdrawal will go under 100
           if(ISAAccount.getBalance() - amountToTransfer < 100) {
               System.out.println("Your transfer will make your new balance less than 100 +" +
                       "please keep 100 and above at all times");
               return;
           }
        }
        if(fromAccount.balance > amountToTransfer) {
            toAccount.setBalance(toAccount.balance += amountToTransfer);
           fromAccount.setBalance(balance -= amountToTransfer);
            System.out.println("Funds successfully .");
        } else {
            System.out.println("Insufficient funds.");
        }
    }
    //NB need to put in BankAcc toSort, preferable generated by the user, which allows us to designate the destination account
    //NB As above with the BankAcc toAccount, i.e. get is from the user typing.

    /*
    https://codereview.stackexchange.com/questions/259695/simple-bank-application-in-java
*/

    public void transactionHistory() {
        this.numberWithdrawals = 0;
        this.numberWithdrawals = 0;
    }


}

